<a href="https://colab.research.google.com/github/madhumitha006/Madhumitha-Codeboosters-internship-2026/blob/main/Day_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
a = pd.read_csv("SOCR-HeightWeight.csv")

In [3]:
a.head()

   Index  Height(Inches)  Weight(Pounds)
0      1        65.78331        112.9925
1      2        71.51521        136.4873
2      3        69.39874        153.0269
3      4        68.21660        142.3354
4      5        67.78781        144.2971

In [4]:
x=a[["Height(Inches)"]]

In [5]:
y=a["Weight(Pounds)"]

In [6]:
a.isnull()

       Index  Height(Inches)  Weight(Pounds)
0      False           False           False
1      False           False           False
2      False           False           False
3      False           False           False
4      False           False           False
...      ...             ...             ...
24995  False           False           False
24996  False           False           False
24997  False           False           False
24998  False           False           False
24999  False           False           False

[25000 rows x 3 columns]

In [7]:
a.isnull().any()

Index             False
Height(Inches)    False
Weight(Pounds)    False
dtype: bool

In [8]:
a.isnull().sum()

Index             0
Height(Inches)    0
Weight(Pounds)    0
dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [11]:
x_train

       Height(Inches)
15920        67.27892
17504        69.22513
19485        68.96742
2572         67.96612
18930        68.91809
...               ...
4598         66.46990
14428        70.01339
20803        68.11271
3486         69.89700
9660         68.49582

[20000 rows x 1 columns]

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
model=LinearRegression()

In [14]:
model.fit(x_train,y_train)

LinearRegression()

In [15]:
model.predict(x_test)

array([113.98350214, 127.63072124, 119.60313901, ..., 115.93105885,
       107.95383698, 128.52046212])

In [16]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [17]:
from sklearn.metrics import mean_absolute_error
y_pred=model.predict(x_test)
mean_absolute_error(y_test,y_pred)

8.041292566276805

In [18]:
mean_absolute_error(y_test,y_pred)

8.041292566276805

In [19]:
mean_squared_error(y_test,y_pred)

102.2862324348714

In [20]:
r2_score(y_test,y_pred)

0.23339732574564365

In [21]:
import joblib

In [22]:
joblib.dump(model,"linear.pk")

['linear.pk']

In [23]:
import pandas as pd
df=pd.read_csv('data.csv')
df.head()
y=df['price']
x=df[['bedrooms','sqft_living','sqft_lot']]
df.isnull()
df.dropna()
df.isnull().any()
df.isnull().sum()
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
x_train

      bedrooms  sqft_living  sqft_lot
1017       6.0         2860      5682
4396       4.0         2110      3750
964        3.0         2060     44866
2741       5.0         3600     17300
2727       3.0         2910     10204
...        ...          ...       ...
3220       2.0         1460      9052
126        4.0         1480      3844
1764       4.0         1830      5175
1075       3.0         1390     10905
2147       3.0         1380      3402

[3680 rows x 3 columns]

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

In [25]:
dt_model=DecisionTreeRegressor(
    max_depth=5,#level in a tree
    random_state=42
)
model=DecisionTreeRegressor()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
mean_squared_error(y_test,y_pred)

884312363282.5002

In [26]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_pred)

249100.1502245141

In [27]:
rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)