<a href="https://colab.research.google.com/github/madhumitha006/Madhumitha-Codeboosters-internship-2026/blob/main/Day_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
a = pd.read_csv("SOCR-HeightWeight.csv")

In [ ]:
a.head()

   Index  Height(Inches)  Weight(Pounds)
0      1        65.78331        112.9925
1      2        71.51521        136.4873
2      3        69.39874        153.0269
3      4        68.21660        142.3354
4      5        67.78781        144.2971

In [ ]:
x=a[["Height(Inches)"]]

In [ ]:
y=a["Weight(Pounds)"]

In [ ]:
a.isnull()

       Index  Height(Inches)  Weight(Pounds)
0      False           False           False
1      False           False           False
2      False           False           False
3      False           False           False
4      False           False           False
...      ...             ...             ...
24995  False           False           False
24996  False           False           False
24997  False           False           False
24998  False           False           False
24999  False           False           False

[25000 rows x 3 columns]

In [ ]:
a.isnull().any()

Index             False
Height(Inches)    False
Weight(Pounds)    False
dtype: bool

In [ ]:
a.isnull().sum()

Index             0
Height(Inches)    0
Weight(Pounds)    0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
x_train

       Height(Inches)
8421         69.37021
6747         72.07034
16809        69.59150
7907         69.41584
12403        68.46486
...               ...
11778        66.22392
12647        70.39459
1952         69.86498
10863        70.57890
3647         66.96921

[20000 rows x 1 columns]

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model=LinearRegression()

In [ ]:
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
model.predict(x_test)

array([133.49011676, 130.89093634, 135.94243895, ..., 124.5448634 ,
       123.53486561, 131.79080591])

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [ ]:
from sklearn.metrics import mean_absolute_error
y_pred=model.predict(x_test)
mean_absolute_error(y_test,y_pred)

8.038687187511352

In [ ]:
mean_absolute_error(y_test,y_pred)

8.038687187511352

In [ ]:
mean_squared_error(y_test,y_pred)

101.67129079033418

In [ ]:
r2_score(y_test,y_pred)

0.24879161436244523

In [ ]:
import joblib

In [ ]:
joblib.dump(model,"linear.pk")

['linear.pk']